/**
 * ElevenLabs Text-to-Speech Demo
 * 
 * Demonstrates converting text to natural-sounding speech using ElevenLabs API.
 * Reference: https://elevenlabs.io/docs/api-reference/text-to-speech
 */

import { ElevenLabsClient } from '@elevenlabs/elevenlabs-js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

// Load environment variables from parent directory
const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '../.env') });

// Available models (from ElevenLabs docs)
const MODELS = {
  FLASH: 'eleven_flash_v2_5',      // Ultra-low latency (~75ms), 50% cheaper
  TURBO: 'eleven_turbo_v2_5',      // Balanced quality/speed (~250ms)
  MULTILINGUAL: 'eleven_multilingual_v2', // Natural-sounding, 29 languages
};

// Popular voice IDs
const VOICES = {
  SARAH: 'EXAVITQu4vr4xnSDxMaL',   // Gentle, calming female voice
  ROGER: 'CwhRBWXzGAHq8TQ4Fs17',   // Laid-back male voice
  ARIA: '9BWtsMINqrJLrRacOk9x',    // Expressive female voice
};

async function main() {
  // Check for API key
  if (!process.env.ELEVENLABS_API_KEY) {
    console.error('❌ ELEVENLABS_API_KEY not found in .env file');
    process.exit(1);
  }

  console.log('🎙️ ElevenLabs Text-to-Speech Demo\n');

  // Initialize client
  const client = new ElevenLabsClient({
    apiKey: process.env.ELEVENLABS_API_KEY,
  });

  // Demo text samples
  const samples = [
    {
      text: "Hello! This is a demo of ElevenLabs text-to-speech. The voice you're hearing is generated by AI.",
      voice: VOICES.SARAH,
      model: MODELS.FLASH,
      name: 'demo-flash',
    },
    {
      text: "Take a deep breath. You're doing great. The classroom environment is calm and supportive.",
      voice: VOICES.SARAH,
      model: MODELS.TURBO,
      name: 'demo-calming',
    },
  ];

  // Create output directory
  const outputDir = path.join(__dirname, 'output');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Generate audio for each sample
  for (const sample of samples) {
    console.log(`📝 Text: "${sample.text.substring(0, 50)}..."`);
    console.log(`🎤 Voice: ${Object.keys(VOICES).find(k => VOICES[k] === sample.voice)}`);
    console.log(`🔧 Model: ${sample.model}`);

    try {
      const startTime = Date.now();

      // Generate speech
      const audioStream = await client.textToSpeech.convert(sample.voice, {
        text: sample.text,
        modelId: sample.model,
        outputFormat: 'mp3_44100_128',
        voiceSettings: {
          stability: 0.6,
          similarityBoost: 0.75,
        },
      });

      // Collect audio chunks
      const chunks = [];
      for await (const chunk of audioStream) {
        chunks.push(chunk);
      }
      const audioBuffer = Buffer.concat(chunks);

      // Save to file
      const outputPath = path.join(outputDir, `${sample.name}.mp3`);
      fs.writeFileSync(outputPath, audioBuffer);

      const elapsed = Date.now() - startTime;
      console.log(`✅ Generated: ${outputPath}`);
      console.log(`⏱️ Time: ${elapsed}ms`);
      console.log(`📊 Size: ${(audioBuffer.length / 1024).toFixed(1)} KB\n`);

    } catch (error) {
      console.error(`❌ Error: ${error.message}\n`);
    }
  }

  console.log('🎉 Demo complete! Check the output/ folder for generated audio files.');
}

main().catch(console.error);
